---
# The main playbook for the user-management role.

- name: Add the ansible management user.
  hosts: linux
  gather_facts: false
  become: true
  vars_files:
    - roles/user-management/vars/vault
  roles:
    - role: user-management