---
# The main playbook for the user-management role.

- name: Add the ansible management user.
  hosts: linux
  gather_facts: false
  remote_user: "{{ provisioned_user }}"
  become: true
  vars_files:
    - roles/user-management/vars/vault
  vars:
    ansible_become_pass: "{{ provisioned_pass }}"
    ansible_ssh_pass: "{{ provisioned_pass }}"
  roles:
    - role: user-management